# Generated by Django 5.0 on 2026-09-12 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='category',
            field=models.CharField(choices=[('primary', 'Primary'), ('junior-high', 'Junior-High'), ('high', 'High'), ('college', 'College')], default='college', max_length=20),
        ),
    ]
