# Generated by Django 5.0 on 2026-09-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_education_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
